commonfields:
  id: 3e8d4481-82af-4b9f-8b27-938c78183595
  version: -1
contentitemexportablefields:
  contentitemfields:
    definitionid: ""
    fromServerVersion: ""
    itemVersion: ""
    packID: ""
    packName: ""
    propagationLabels:
    - all
    toServerVersion: ""
dockerimage: demisto/python3:3.10.5.31928
enabled: true
engineinfo: {}
mainengineinfo: {}
name: TestAutomation
pswd: ""
runas: DBotWeakRole
runonce: false
script: ""
scripttarget: 0
subtype: python3
tags: []
type: python
